data_file = "public/data.json"
public_dir = "public"
qr_dir = "public/qr"

[verifier]
name = "Local Metadata Signer"
public_key = "ee6a7cd8146e9f02e4ae9f59908a5b513186e786696c6afe9644ff59bdbdbe7c"

[[chains]]
name = "node-subtensor"
rpc_endpoint = "wss://lite.chain.opentensor.ai:443"

[chains.github_release]
owner = "opentensor"
repo = "subtensorv3"
genesis_hash = "0x2f0555cc76fc2840a25a6ea3b9637146806f1f44b090c175ffde2a7e5ab36c03"