data_file_path = "src/chains.json"
public_dir_path = "public"

[public]
signed_qr_dir = "qr/signed"
unsigned_qr_dir = "qr/unsigned"

[[chains]]
name = "polkadot"
rpc_endpoint = "wss://rpc.polkadot.io"
color = "#e6007a"
icon_path = "icons/polkadot.ico"

[[chains]]
name = "kusama"
rpc_endpoint = "wss://kusama-rpc.polkadot.io"
color = "#000000"
icon_path = "icons/kusama.ico"
