data_file = "public/data.json"
public_dir = "public"
qr_dir = "public/qr"

[verifier]
name = "Novasama Technologies"
public_key = "16d5a6266345874d8f5b7f88a6619711b2829b52b2865826b1ecefb62beef34f"

[[chains]]
name = "bifrost"
color = "#5a25f0"
logo = "Bifrost_Kusama.svg"
rpc_endpoint = "wss://bifrost-parachain.api.onfinality.io/public-ws"
genesis_hash = "0x9f28c6a68e0fc9646eff64935684f6eeeece527e37bbe1f213d22caa1d9d6bed"

[[chains]]
name = "acala"
color = "#645AFF"
logo = "Acala.svg"
rpc_endpoint = "wss://acala-rpc.dwellir.com"
genesis_hash = "0xfc41b9bd8ef8fe53d58c7ea67c794c7ec9a73daf05e6d54b14ff6342c99ba64c"

[[chains]]
name = "statemine"
color = "#113911"
logo = "Statemine.svg"
rpc_endpoint = "wss://statemine.api.onfinality.io/public-ws"
genesis_hash = "0x48239ef607d7928874027a43a67689209727dfb3d3dc5e5b03a39bdc2eda771a"

[[chains]]
name = "karura"
color = "#ff4c3b"
logo = "Karura.svg"
rpc_endpoint = "wss://karura-rpc-0.aca-api.network"
genesis_hash = "0xbaf5aabe40646d11f0ee8abbdc64f4a4b7674925cba08e4a05ff9ebed6e2126b"

[[chains]]
name = "heiko"
color = "#42d5de"
logo = "ParallelHeiko.svg"
rpc_endpoint = "wss://heiko-rpc.parallel.fi"
genesis_hash = "0x64a1c658a48b2e70a7fb1ad4c39eea35022568c20fc44a6e2e3d0a57aee6053b"

[[chains]]
name = "shiden"
color = "#5923B2"
logo = "Shiden.svg"
rpc_endpoint = "wss://rpc.shiden.astar.network"
genesis_hash = "0xf1cf9022c7ebb34b162d5b5e34e705a5a740b2d0ecc1009fb89023e62a488108"

[[chains]]
name = "basilisk"
color = "#9eec1b"
logo = "Basilisk.svg"
rpc_endpoint = "wss://rpc-01.basilisk.hydradx.io"
genesis_hash = "0xa85cfb9b9fd4d622a5b28289a02347af987d8f73fa3108450e2b4a11c1ce5755"

[[chains]]
name = "altair"
color = "#ffb700"
logo = "Altair.svg"
rpc_endpoint = "wss://fullnode.altair.centrifuge.io"
genesis_hash = "0xaa3876c1dc8a1afcc2e9a685a49ff7704cfd36ad8c90bf2702b9d1b00cc40011"

[[chains]]
name = "khala"
color = "#03f3f3"
logo = "Khala.svg"
rpc_endpoint = "wss://khala-api.phala.network/ws"
genesis_hash = "0xd43540ba6d3eb4897c28a77d48cb5b729fea37603cbbfc7a86a73b72adb3be8d"

[[chains]]
name = "kilt-spiritnet"
color = "#8c145a"
logo = "KILT_Spiritnet.svg"
rpc_endpoint = "wss://spiritnet.kilt.io/"

[[chains]]
name = "calamari"
color = "#000000"
logo = "Calamari.svg"
rpc_endpoint = "wss://ws.calamari.systems/"

[[chains]]
name = "quartz"
color = "#FF4D6A"
logo = "Quartz.svg"
rpc_endpoint = "wss://quartz.api.onfinality.io/public-ws"

[[chains]]
name = "pioneer-runtime"
color = "#000000"
logo = "Bit.Country_Pioneer.svg"
rpc_endpoint = "wss://pioneer.api.onfinality.io/public-ws"

[[chains]]
name = "astar"
color = "#1b6dc1d9"
logo = "Astar.svg"
rpc_endpoint = "wss://astar.api.onfinality.io/public-ws"

[[chains]]
name = "parallel"
color = "#ef18ac"
logo = "Parallel.svg"
rpc_endpoint = "wss://rpc.parallel.fi"

[[chains]]
name = "clover-mainnet"
color = "linear-gradient(to right, #52ad75, #7cc773)"
logo = "CLV_Parachain.svg"
rpc_endpoint = "wss://rpc-para.clover.finance"

[[chains]]
name = "statemint"
color = "#86e62a"
logo = "Statemint.svg"
rpc_endpoint = "wss://statemint-rpc.polkadot.io"

[[chains]]
name = "subsocial"
color = "#b9018c"
logo = "Subsocial_Solochain.svg"
rpc_endpoint = "wss://arch.subsocial.network"

[[chains]]
name = "robonomics"
color = "#2949d3"
logo = "Robonomics.svg"
rpc_endpoint = "wss://kusama.rpc.robonomics.network/"

[[chains]]
name = "encointer-parachain"
color = "#0000cc"
logo = "Encointer.svg"
rpc_endpoint = "wss://api.kusama.encointer.org"

[[chains]]
name = "kintsugi-parachain"
color = "#1a0a2d"
logo = "Kintsugi.svg"
rpc_endpoint = "wss://api-kusama.interlay.io/parachain"

[[chains]]
name = "picasso"
color = "#000000"
logo = "Picasso.svg"
rpc_endpoint = "wss://picasso-rpc.composable.finance"

[[chains]]
name = "zeitgeist"
color = "linear-gradient(180deg, rgba(32,90,172,1) 0%, rgba(26,72,138,1) 50%, rgba(13,36,69,1) 100%)"
logo = "Zeitgeist.svg"
rpc_endpoint = "wss://zeitgeist-rpc.dwellir.com"

[[chains]]
name = "hydradx"
color = "#f653a2"
logo = "HydraDX.svg"
rpc_endpoint = "wss://rpc-01.hydradx.io"

[[chains]]
name = "kico"
color = "#29B58D"
logo = "KICO.svg"
rpc_endpoint = "wss://rpc.kico.dico.io"

[[chains]]
name = "litmus-parachain"
color = "#6822fb"
logo = "Litmus.svg"
rpc_endpoint = "wss://rpc.litmus-parachain.litentry.io"

[[chains]]
name = "crab parachain"
color = "#7C30DD"
logo = "Crab.svg"
rpc_endpoint = "wss://crab-parachain-rpc.darwinia.network/"

[[chains]]
name = "subsocial-parachain"
color = "#69058C"
logo = "Subsocial_Parachain.svg"
rpc_endpoint = "wss://para.subsocial.network"

[[chains]]
name = "crust-collator"
color = "#ff8812"
logo = "Crust_Shadow.svg"
rpc_endpoint = "wss://rpc2-shadow.crust.network/"

[[chains]]
name = "integritee-parachain"
color = "#658ea9"
logo = "Integritee.svg"
rpc_endpoint = "wss://integritee-kusama.api.onfinality.io/public-ws"

[[chains]]
name = "centrifuge"
color = "#fcc367"
logo = "Centrifuge.svg"
rpc_endpoint = "wss://fullnode.parachain.centrifuge.io"

[[chains]]
name = "efinity"
color = "#496ddb"
logo = "Efinity.svg"
rpc_endpoint = "wss://rpc.efinity.io"

[[chains]]
name = "interlay-parachain"
color = "#3E96FF"
logo = "Interlay.svg"
rpc_endpoint = "wss://interlay.api.onfinality.io/public-ws"

[[chains]]
name = "nodle-para"
color = "#1ab394"
logo = "Nodle.svg"
rpc_endpoint = "wss://nodle-parachain.api.onfinality.io/public-ws"

[[chains]]
name = "turing"
color = "#A8278C"
logo = "Turing.svg"
rpc_endpoint = "wss://turing.api.onfinality.io/public-ws"

[[chains]]
name = "aleph-node"
color = "#00CCAB"
logo = "AlephZero.svg"
rpc_endpoint = "wss://ws.azero.dev"

#todo Composable finance. SS58 code is different.
#[[chains]]
#name = "composable-finance"
#color = "#C90E8A"
#logo = "Composable.svg"
#rpc_endpoint = "wss://composable-rpc.dwellir.com"

#TODO polkadex parachain. Names are different.
#[[chains]]
#name = "polkadex-solochain"
#color = "#7C30DD"
#logo = "Polkadex.svg"
#rpc_endpoint = "wss://polkadex.api.onfinality.io/public-ws"

[[chains]]
name = "origintrail-parachain"
color = "#FB5DEB"
logo = "OriginTrail.svg"
rpc_endpoint = "wss://parachain-rpc.origin-trail.network"

[[chains]]
name = "bifrost_polkadot"
color = "#5a25f0"
logo = "Bifrost_Polkadot.svg"
rpc_endpoint = "wss://hk.p.bifrost-rpc.liebi.com/ws"

[[chains]]
name = "litentry-parachain"
color = "linear-gradient(45deg, #5cc27c 0%, #6de98f 100%)"
logo = "Litentry.svg"
rpc_endpoint = "wss://rpc.litentry-parachain.litentry.io"

[[chains]]
name = "unique"
color = "#40BCFF"
logo = "Unique.svg"
rpc_endpoint = "wss://eu-ws.unique.network/"

[[chains]]
name = "dora ksm parachain"
color = "#FF761C"
logo = "DoraFactory.svg"
rpc_endpoint = "wss://kusama.dorafactory.org"

[[chains]]
name = "mangata-parachain"
color = "#030408"
logo = "MangataX.svg"
rpc_endpoint = "wss://mangata-x.api.onfinality.io/public-ws"

[[chains]]
name = "pichiu"
color = "#ed007e"
logo = "Pichiu.svg"
rpc_endpoint = "wss://kusama.kylin-node.co.uk"

[[chains]]
name = "kabocha-parachain"
color = "#f53485"
logo = "Kabocha.svg"
rpc_endpoint = "wss://kabocha.jelliedowl.com"

[[chains]]
name = "datahighway-parachain"
color = "linear-gradient(-90deg, #9400D3 0%, #5A5CA9 50%, #00BFFF 100%)"
logo = "Tanganika_DataHighway.svg"
rpc_endpoint = "wss://tanganika.datahighway.com"

[[chains]]
name = "bajun"
color = "#161212"
logo = "Bajun.svg"
rpc_endpoint = "wss://rpc-parachain.bajun.network"

#todo Imbue. SS58 code is different.
#[[chains]]
#name = "imbue"
#color = "#baff36"
#logo = "Imbue.svg"
#rpc_endpoint = "wss://imbue-kusama.imbue.network"

# Test networks
[[chains]]
name = "westmint"
color = "#77bb77"
logo = "Westmint_Testnet.svg"
rpc_endpoint = "wss://westmint-rpc.polkadot.io"

[[chains]]
name = "mandala"
color = "#173DC9"
logo = "Acala_Mandala_Testnet.svg"
rpc_endpoint = "wss://acala-mandala.api.onfinality.io/public-ws/"

