data_file = "src/chains.json"
public_dir = "public"
qr_dir = "public/qr"

[verifier]
name = "Parity"
public_key = "c46a22b9da19540a77cbde23197e5fd90485c72b4ecf3c599ecca6998f39bd57"

[[chains]]
name = "polkadot"
rpc_endpoint = "wss://rpc.polkadot.io"

[[chains]]
name = "kusama"
rpc_endpoint = "wss://kusama-rpc.polkadot.io"

[[chains]]
name = "westend"
rpc_endpoint = "wss://westend-rpc.polkadot.io"

# [[chains]]
# name = "karura"
# rpc_endpoint = "wss://karura.api.onfinality.io/public-ws"
# token_unit = "KAR"
# token_decimals = 12