data_file = "public/data.json"
public_dir = "public"
qr_dir = "public/qr"

[verifier]
name = "insipx"
public_key = "6274199fd286efcd04b0234aec390311f312a3af78c3917f8280d16597f40d2a"

[[chains]]
name = "parallel"
rpc_endpoints = [
    'wss://rpc.parallel.fi',
    'wss://parallel.api.onfinality.io/public-ws',
]
testnet = false
verifier = "insipx"

[[chains]]
name = 'efinity'
title = 'Efinity'
color = '#496ddb'
icon = 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/chains/gradient/Efinity.svg'
rpc_endpoints = [
    'wss://rpc.efinity.io',
    'wss://efinity-rpc.dwellir.com',
]
testnet = false
verifier = 'insipx'

[[chains]]
name = 'astar'
title = 'Astar'
color = '#1b6dc1'
icon = 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/chains/gradient/Astar.svg'
rpc_endpoints = [
    'wss://rpc.astar.network',
    'wss://astar.api.onfinality.io/public-ws',
]
testnet = false
verifier = 'insipx'

[[chains]]
name = 'karura'
title = 'Karura'
color = '#ff4c3b'
icon = 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/chains/gradient/Karura.svg'
rpc_endpoints = [
    'wss://karura-rpc.dwellir.com',
    'wss://karura-rpc-0.aca-api.network',
    'wss://karura-rpc-1.aca-api.network',
    'wss://karura-rpc-2.aca-api.network/ws',
    'wss://karura-rpc-3.aca-api.network/ws',
]
testnet = false
verifier = 'insipx'

[[chains]]
name = 'shiden'
title = 'Shiden'
color = '#5923B2'
icon = 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/chains/gradient/Shiden.svg'
rpc_endpoints = [
    'wss://rpc.shiden.astar.network',
    'wss://shiden.api.onfinality.io/public-ws',
    'wss://rpc.pinknode.io/shiden/explorer',
]
testnet = false
verifier = 'insipx'

[[chains]]
name = 'basilisk'
title = 'Basilisk'
color = '#9eec1b'
icon = 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/chains/gradient/Basilisk.svg'
rpc_endpoints = [
    'wss://rpc.basilisk.cloud',
    'wss://basilisk-rpc.dwellir.com',
]
testnet = false
verifier = 'insipx'


[[chains]]
name = 'heiko'
title = 'Parallel Heiko'
color = '#42d5de'
icon = 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/chains/gradient/ParallelHeiko.svg'
rpc_endpoints = [
    'wss://heiko-rpc.parallel.fi',
    'wss://parallel-heiko.api.onfinality.io/public-ws',
]
testnet = false
verifier = 'insipx'


[[chains]]
name = 'statemint'
title = 'Statemint'
color = '#86e62a'
icon = 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/chains/gradient/Statemint.svg'
rpc_endpoints = [
    'wss://statemint-rpc.polkadot.io',
    'wss://statemint.api.onfinality.io/public-ws',
    'wss://statemint-rpc.dwellir.com',
]
testnet = false
verifier = 'insipx'

[[chains]]
name = 'picasso'
title = 'Picasso'
color = '#000000'
icon = 'https://raw.githubusercontent.com/nova-wallet/nova-utils/master/icons/chains/gradient/Picasso.svg'
rpc_endpoints = ['wss://picasso-rpc.composable.finance']
testnet = false
verifier = 'insipx'

