name: Check updates

on:
  schedule:
    - cron: '0 */4 * * *'
  pull_request:
    branches:
      - master

env:
  SIGN_ME_PREFIX: sign-me

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: ðŸ›Ž Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: ./.github/workflows/rust-install

      - name: Try to checkout exising PR branch
        id: checkout-pr
        run: |
          SIGN_ME_BRANCH=$(git branch -r --list 'origin/${SIGN_ME_PREFIX}-*' --sort=-refname | head -n 1)
          if [ -z "$SIGN_ME_BRANCH" ]
          then
            switched="false"
          else
            git checkout $SIGN_ME_BRANCH
            switched="true"
          fi
          echo "::set-output name=switched::$switched"

      - name: âš™ Run QR updater
        run: make updater

      - name: âš™ Run collector
        run: make collector

      - name: âš™ Run cleaner
        run: make cleaner

      - name: ðŸ“Œ Commit changes if PR exists
        if: ${{ steps.checkout-pr.outputs.switched == 'true' }}
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add .
          git commit -m "add unsigned QR code" || true
          git push

      - name: New PR branch
        if: ${{ steps.checkout-pr.outputs.switched == 'false' }}
        id: new-branch
        run: |
          NAME="$AUTOMATED_BRANCH-$(date '+%Y-%m-%d')"
          echo "::set-output name=name::$NAME"

      - name: Create Pull Request if not exist
        if: ${{ steps.checkout-pr.outputs.switched == 'false' }}
        uses: peter-evans/create-pull-request@f22a7da129c901513876a2380e2dae9f8e145330
        with:
          commit-message: add unsigned QR codes
          branch: ${{ steps.new-branch.outputs.name }}
          delete-branch: true
          base: master
          title: '[Automated] Sign new QR codes'
          body: |
            - [ ] Clone the repo and checkout this branch
            - [ ] Run `make signer` to sign files
            - [ ] Commit changes and push
          draft: true
          reviewers: prybalko
