name: Check updates

on:
  schedule:
    - cron: '0 */6 * * *'

env:
  AUTOMATED_BRANCH: qr-generator/to-sign

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: ðŸ›Ž Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Try to checkout to the existing automated branch
        id: checkout-automated
        run: |
          ok=$(git checkout $AUTOMATED_BRANCH >> /dev/null && echo "true" || echo "false")
          echo "::set-output name=ok::$ok"

      - name: ðŸ”§ Install stable toolchain
        uses: actions-rs/toolchain@b2417cde72dcf67f306c0ae8e0828a81bf0b189f
        with:
          profile: minimal
          toolchain: stable

      - name: âš¡ Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            rust/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('./rust/Cargo.lock') }}

      - name: âš™ Run QR updater
        run: make updater

      - name: âš™ Run collector
        run: make collector

      - name: âš™ Run cleaner
        run: make cleaner

      - name: ðŸ“Œ Commit changes if PR exists
        if: ${{ steps.checkout-automated.outputs.ok == 'true' }}
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git commit -am "add unsigned QR code" || true
          git push

      - name: Create Pull Request if not exist
        if: ${{ steps.checkout-automated.outputs.ok == 'false' }}
        uses: peter-evans/create-pull-request@f22a7da129c901513876a2380e2dae9f8e145330
        with:
          commit-message: add unsigned QR codes
          branch: ${{ env.AUTOMATED_BRANCH }}
          delete-branch: true
          base: master
          title: '[Automated] Sign new QR codes'
          add-paths: |
            public/qr
          body: |
            - [ ] Sign new QR codes and push them to this branch
          assignees: prybalko
          reviewers: prybalko
