name: Frontend test

on:
  pull_request:
    branches:
      - master

jobs:
  frontend-test:
    runs-on: ubuntu-latest

    steps:
      - name: ðŸ›Ž Checkout
        uses: actions/checkout@v4

      - name: ðŸ”§ Install yarn
        run: npm install -g yarn prettier

      - name: Get yarn cache path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - name: âš¡ NPM Cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}

      - name: ðŸ”§ Install dependencies
        run: yarn

      - name: Check lint
        run: |
          yarn lint --max-warnings=0
          yarn prettier --check "src/**/*.(tsx|ts)"

      - name: Pretend we have data.json and run tests
        run: cp public/test-file.json public/data.json && yarn test
