name: Check updates

on:
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 */6 * * *'

env:
  AUTOMATED_BRANCH: qr-generator/to-sign

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: ðŸ›Ž Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Hack for not generating already generated QR codes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git merge origin/$AUTOMATED_BRANCH && git reset HEAD~ || true

      - name: ðŸ”§ Install stable toolchain
        uses: actions-rs/toolchain@b2417cde72dcf67f306c0ae8e0828a81bf0b189f
        with:
          toolchain: stable

      - name: âš¡ Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            rust/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('./rust/Cargo.lock') }}

      - name: âš™ Run QR generator
        run: make generator

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@f22a7da129c901513876a2380e2dae9f8e145330
        with:
          commit-message: add unsigned QR codes
          branch: $AUTOMATED_BRANCH
          delete-branch: true
          base: master
          title: '[Automated] Sign new QR codes'
          add-paths: |
            public/qr
          body: |
            - [ ] Sign new QR codes and push them to this branch
            - [ ] Remove  `unsigned_`  files
          assignees: prybalko
          reviewers: prybalko
